### ISSUE TITLE
Error while trying to install FaceShift in OSX High Sierra

### ISSUE THREAD

**Issue by GratefulDave** [FaceShift/faceshift#8]
Hi,

I am a total n00b. Not sure of the right questions to ask. Starting to take online coding. Would love to install this.

[yarn-error.log](https://github.com/FaceShift/faceshift/files/2242057/yarn-error.log)

**Comment by JakeMathews** [comment]
Hi @GratefulDave ,

This was a school project and is no longer being worked on. It was difficult to install because it required OS dependent drivers and a very specific version of NodeJS to work. If you are looking to try to build or modify a project I suggest a simpler project.
